### ISSUE TITLE
catchError for RuleT is bottom

### ISSUE THREAD

**Issue by isovector** [TOTBWF/refinery#5]
```haskell
  catchError r h = coerce $ flip catchError h $ coerce r
```

these coerces are turning into `id` :) 

It can't be implemented in terms of the underlying `ProofStateT` because that is only defined when `ext' ~ ext`, which is not true for `RuleT`

**Comment by TOTBWF** [comment]
Turns out that catching errors in a `RuleT` is not the right design! This has been subsumed by unsolvable holes, so this is no longer relevant as of #15.
